#!/usr/bin/env python

'''
``software`` module contains functionality to parse out
latest software versions from respective vendors' web sites.
'''

import software_versions.reparser as sre
import software_versions.domparser as sdom

STABLE_SENDMAIL_URL = sre.STABLE_SENDMAIL_URL
STABLE_SENDMAIL_PATTERN = sre.STABLE_SENDMAIL_PATTERN

STABLE_BIND_URL = sre.STABLE_BIND_URL
STABLE_BIND_PATTERN = sre.STABLE_BIND_PATTERN

STABLE_DHCP_URL = sre.STABLE_DHCP_URL
STABLE_DHCP_PATTERN = sre.STABLE_DHCP_PATTERN

STABLE_CYRUS_IMAP_URL = sre.STABLE_CYRUS_IMAP_URL
STABLE_CYRUS_IMAP_PATTERN = sre.STABLE_CYRUS_IMAP_PATTERN

STABLE_APACHE_URL = sre.STABLE_APACHE_URL
STABLE_APACHE_PATTERN = sre.STABLE_APACHE_PATTERN

STABLE_SQUID_URL = sre.STABLE_SQUID_URL
STABLE_SQUID_PATTERN = sre.STABLE_SQUID_PATTERN

STABLE_CANIT_URL = sre.STABLE_CANIT_URL
STABLE_CANIT_PATTERN = sre.STABLE_CANIT_PATTERN

STABLE_PSQL_URL = sre.STABLE_PSQL_URL
STABLE_PSQL_PATTERN = sre.STABLE_PSQL_PATTERN

STABLE_SQUIRRELMAIL_URL = sre.STABLE_SQUIRRELMAIL_URL
STABLE_SQUIRRELMAIL_PATTERN = sre.STABLE_SQUIRRELMAIL_PATTERN

STABLE_OPENLDAP_URL = sre.STABLE_OPENLDAP_URL
STABLE_OPENLDAP_PATTERN = sre.STABLE_OPENLDAP_PATTERN

STABLE_PLA_URL = sre.STABLE_PLA_URL
STABLE_PLA_PATTERN = sre.STABLE_PLA_PATTERN

STABLE_POSTFIX_URL = sre.STABLE_POSTFIX_URL
STABLE_POSTFIX_PATTERN = sre.STABLE_POSTFIX_PATTERN

STABLE_NGINX_URL = sre.STABLE_NGINX_URL
STABLE_NGINX_PATTERN = sre.STABLE_NGINX_PATTERN

STABLE_MYSQL_URL = sre.STABLE_MYSQL_URL
STABLE_MYSQL_PATTERN = sre.STABLE_MYSQL_PATTERN

STABLE_PROFTPD_URL = sre.STABLE_PROFTPD_URL
STABLE_PROFTPD_PATTERN = sre.STABLE_PROFTPD_PATTERN

STABLE_VSFTPD_URL = sre.STABLE_VSFTPD_URL
STABLE_VSFTPD_PATTERN = sre.STABLE_VSFTPD_PATTERN

STABLE_SENDMAILANALYZER_URL = sre.STABLE_SENDMAILANALYZER_URL
STABLE_SENDMAILANALYZER_PATTERN = sre.STABLE_SENDMAILANALYZER_PATTERN

STABLE_DJANGO_URL = sre.STABLE_DJANGO_URL
STABLE_DJANGO_PATTERN = sre.STABLE_DJANGO_PATTERN

STABLE_HPBIOS_URL = sre.STABLE_HPBIOS_URL
STABLE_HPBIOS_PATTERN = sre.STABLE_HPBIOS_PATTERN

__all__ = [
    "STABLE_SENDMAIL_URL", "STABLE_SENDMAIL_PATTERN",
    "STABLE_BIND_URL", "STABLE_BIND_PATTERN",
    "STABLE_CYRUS_IMAP_URL", "STABLE_CYRUS_IMAP_PATTERN",
    "STABLE_APACHE_URL", "STABLE_APACHE_PATTERN",
    "STABLE_SQUID_URL", "STABLE_SQUID_PATTERN",
    "STABLE_CANIT_URL", "STABLE_CANIT_PATTERN",
    "STABLE_PSQL_URL", "STABLE_PSQL_PATTERN",
    "STABLE_SQUIRRELMAIL_URL", "STABLE_SQUIRRELMAIL_PATTERN",
    "STABLE_OPENLDAP_URL", "STABLE_OPENLDAP_PATTERN",
    "STABLE_PLA_URL", "STABLE_PLA_PATTERN",
    "STABLE_POSTFIX_URL", "STABLE_POSTFIX_PATTERN",
    "STABLE_NGINX_URL", "STABLE_NGINX_PATTERN",
    "STABLE_MYSQL_URL", "STABLE_MYSQL_PATTERN",
    "STABLE_PROFTPD_URL", "STABLE_PROFTPD_PATTERN",
    "STABLE_VSFTPD_URL", "STABLE_VSFTPD_PATTERN",
    "STABLE_SENDMAILANALYZER_URL", "STABLE_SENDMAILANALYZER_PATTERN",
    "STABLE_DJANGO_URL", "STABLE_DJANGO_PATTERN",
    "STABLE_HPBIOS_URL", "STABLE_HPBIOS_PATTERN"
]
